name: image_classification_mobilenet
description: Image Classification using mobilenet.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  image: ^4.0.17
  tflite_flutter: ^0.10.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/mobilenet/

flutter_launcher_icons:
  image_path: 'assets/images/logo.png'
  android: 'ic_launcher'
  ios: true
  remove_alpha_ios: true
